version: "2"

services:
  develop:
    image: docker.gwrk.pl:5043/develop71
    volumes:
      - ./:/var/www
      - ./data/nothing:/var/www/data
      - ~/.ssh/id_rsa:/home/gowork/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/home/gowork/.ssh/id_rsa.pub
      - ./zsh_history:/home/gowork/.zsh_history
      - ~/.gitconfig:/home/gowork/.gitconfig
      - ~/.ssh/known_hosts:/home/gowork/.ssh/known_hosts
