version: "2"

services:
  develop:
    build: docker/console
    volumes:
      - ./:/var/www
      - ~/.ssh/id_rsa:/home/subpackager/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/home/subpackager/.ssh/id_rsa.pub
      - ./zsh_history:/home/subpackager/.zsh_history
      - ~/.gitconfig:/home/subpackager/.gitconfig
      - ~/.ssh/known_hosts:/home/subpackager/.ssh/known_hosts
